### ISSUE TITLE
Inicio de Jogo(User stories)

### ISSUE THREAD

**Issue by brunomprk** [pds2-dcc-ufmg/2023-1-exercicio-revisao-refatoracao#1]
Gostaria que como desenvolvedor que os jogadores tivessem que incluir seus nomes(reais ou fictícios) para serem identificados durante o jogo.

**Requerimento**
Exibição de inscrição para o jogador(a)

**Comment by douglasmacharet** [comment]
NÃO DEVE SER COLOCADO AQUI.
